import Head from "next/head";
import Image from "next/image";
import MainMenu from "../components/menu/MainMenu";
import Home from "../components/layouts/Home";


export default function Homee() {
  return (
    <div >
      <Head>
        <title>Create Next Appp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        {/* <Titlepage title="home"/> */}
        <Home />
        {/* <Dashboard/> */}
      </main>
    </div>
  );
}
