import Head from 'next/head'
import LeftNavbar from '../components/layouts/navbarleft/navbarleft'
 import Image from 'next/image'
import Dashboard from '../components/layouts/dashboard/dashboard'

export default function Home() {
  return (
    <div className="container">
    <Head>
      <title>Create Next Appp</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="main">
    {/* <LeftNavbar/> */}
    <Dashboard/>
    </main>
  </div>
  )
}
